services:
  frontend:
    image: frontend:latest
    pull_policy: never
    container_name: frontend
    expose:
      - '8080'
    networks:
      - backend_net
      - frontend_net
    depends_on:
      - backend
    healthcheck:
      test: ['CMD', 'wget', '-q', '--spider', 'http://localhost:8080']
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 10s
