services:
  waf:
    image: owasp/modsecurity-crs:nginx
    container_name: waf
    restart: unless-stopped
    networks:
      - frontend_net
    ports:
      - '80:8080'
      - '443:8443'
    volumes:
      - ./certs:/etc/nginx/certs:ro
      - ./tmp:/var/log/modsecurity/host:rw
      - ./conf.d/global_tuning.conf:/etc/nginx/conf.d/global_tuning.conf:ro
      - ./conf.d/security_logic.conf:/etc/nginx/conf.d/z_rate_limit_apply.conf:ro
    depends_on:
      frontend:
        condition: service_healthy
    environment:
      - MODSEC_AUDIT_ENGINE=on
      - MODSEC_AUDIT_LOG=/var/log/modsecurity/host/audit.log
      - LOGLEVEL=warn
      - ERRORLOG=/var/log/modsecurity/host/error.log
      - SSL_OCSP_STAPLING=off
      - MAX_FILE_SIZE=5000000
      - ALLOWED_METHODS=GET POST PUT DELETE
      # --- Webserver Basis ---
      - SERVER_NAME=${SERVER_NAME:-localhost}
      - BACKEND=http://frontend:8080
      - PORT=8080
      - SSL_PORT=8443

      # --- SSL Hardening ---
      - SSL_CERT_FILE=/etc/nginx/certs/dev.crt
      - SSL_CERT_KEY_FILE=/etc/nginx/certs/dev.key
      - SSL_PROTOCOLS=TLSv1.2 TLSv1.3

      # --- WAF Tuning (Maximale Sicherheit) ---
      - SECURITY_ENGINE=On
      - PARANOIA=2
      - ANOMALY_INBOUND_THRESHOLD=5
      - ANOMALY_OUTBOUND_THRESHOLD=4

      # --- Nginx Limits ---
      - WORKER_CONNECTIONS=1024
      - CLIENT_MAX_BODY_SIZE=10M
