import { z } from 'zod';

/**
 * Zod schema for validating candidate data.
 * Maps directly to the "candidates" table in the database.
 *
 * Database mapping:
 * - id: UUID
 * - lastname: TEXT NOT NULL
 * - firstname: TEXT NOT NULL
 * - mtknr: TEXT
 * - faculty: TEXT
 * - keyword: TEXT
 * - notes: TEXT
 * - approved: BOOLEAN NOT NULL DEFAULT FALSE
 *
 * This schema is used for validating input when creating or updating
 * candidate entries. Fields generated by the database (id) are excluded here.
 */

/**
 * Schema for a single candidate record (input).
 * All required DB fields remain required here (firstname, lastname).
 * Optional DB fields are optional here as well (mtknr, faculty, keyword, notes).
 * Approved is optional on input but defaults to false.
 */

export const CANDIDATE_CSV_MAPPING = {
  uid: 'uid',
  Nachname: 'lastname',
  Vorname: 'firstname',
  MatrikelNr: 'mtknr',
  Fakultät: 'faculty',
  Schlüsselworte: 'keyword',
  Notizen: 'notes',
  IstZugelassen: 'approved',
};

export const candidateSchema = z.object({
  uid: z.string().trim().min(1, 'uid darf nicht leer sein'),
  Nachname: z
    .string()
    .trim()
    .min(1, 'Nachname darf nicht leer sein')
    .max(100, 'Nachname darf maximal 100 Zeichen lang sein')
    .regex(/^[a-zA-ZäöüßÄÖÜ\s\-'.]+$/, 'Nachname enthält ungültige Zeichen.'),

  Vorname: z
    .string()
    .trim()
    .min(1, 'Vorname darf nicht leer sein')
    .max(100, 'Vorname darf maximal 100 Zeichen lang sein')
    .regex(/^[a-zA-ZäöüßÄÖÜ\s\-'.]+$/, 'Vorname enthält ungültige Zeichen.'),

  MatrikelNr: z
    .string()
    .trim()
    .max(20)
    .regex(/^\d*$/, 'Matrikelnummer darf nur Ziffern enthalten')
    .optional(),

  Fakultät: z.string().trim().max(50).optional(),

  Schlüsselworte: z.string().trim().max(100).optional(),

  Notizen: z.string().trim().max(500).optional(),

  IstZugelassen: z.preprocess((val) => {
    if (typeof val === 'string') {
      const lower = val.toLowerCase().trim();
      return ['true', '1', 'ja', 'yes', 'wahr'].includes(lower);
    }
    return Boolean(val);
  }, z.boolean().optional().default(false)),
});

/**
 * Schema for validating an array of candidate records.
 * Ensures at least one candidate is present.
 */
export const candidateList = z
  .array(candidateSchema)
  .min(1, 'Die Liste muss mindestens einen Kandidaten enthalten');

/**
 * Schema for candidate records as stored and returned by the database.
 * Includes the autogenerated UUID "id" and the required "approved" field.
 */
export const candidateDb = candidateSchema.extend({
  id: z.uuid({ message: 'ID muss eine gültige UUID sein' }),
  approved: z.boolean(),
});
